# ScrimList

ScrimList automatically numbers the top level topics for any course in Scrimba.
This helps learners quickly identify the number and sequence of topics for a course.
There is no need to manually count or guess the number of topics when learning on Scrimba.
As a learner on Scrimba, I have developed this extension independently.
This extension is not officially endorsed or affiliated with Scrimba.

* DONE Ensure it works for most courses, tutorials and paths and for all siblings.
** It should work for simple courses with a list of scrims like the "Learn Python" course.
** It should work for paths (Fullstack Developer path) or advanced tutorials (TypeScript) with nested content.
** Ensure all topics are numbered including "Certificate of Completion" and the like.
* DONE Enable or disable the extension for convenience, ignore opened tabs - set badge in icon.
** No need to reload existing pages or tabs that have already been opened (user needs to reload them)
* TODO Dynamic functionality - ensure numbering loads when the user visits a page via multiple clicks.
** Internal routing within the page must result in correct result based on current state.
** Check if possible to dynamically reload the current page when switched ON or OFF.
** Refactor the implementation while ensuring dynamic, other features work as expected.
